language: php
php:
  - 5.4
  - 5.5
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]
branches:
  only:
    - master
    - develop
script:
  - composer self-update
  - composer --no-ansi install
  - ./vendor/bin/phpunit --verbose -c tests/phpunit.xml.travis
